version: '3.8'

services:
  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    ports:
      - "9000:9000"
    volumes:
      - ./eureka-server:/app
    working_dir: /app
    command: ["java", "-jar", "target/eureka-server.jar"]
    depends_on:
      - product-service
      - order-service

  product-service:
    image: openjdk:17-jdk-slim
    container_name: product-service
    ports:
      - "8081:8081"
    volumes:
      - ./product-service:/app
    working_dir: /app
    command: ["java", "-jar", "target/product-service.jar"]
    depends_on:
      - eureka-server

  order-service:
    image: openjdk:17-jdk-slim
    container_name: order-service
    ports:
      - "8082:8082"
    volumes:
      - ./order-service:/app
    working_dir: /app
    command: ["java", "-jar", "target/order-service.jar"]
    depends_on:
      - eureka-server